#!/bin/bash -eux

CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='./test-env/run-test debian-trixie' \
  cargo nextest run \
    --release \
    --features test-env-vm \
    --test options \
    --stress-count 20 \
    --failure-output immediate-final \
    --success-output never \
    -- \
    "$@"

CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='./test-env/run-test debian-trixie' \
  cargo nextest run \
    --release \
    --features test-env-vm \
    --test systemd-run \
    --stress-count 20 \
    --test-threads=1 \
    --failure-output immediate-final \
    --success-output never \
    -- \
    "$@"

CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='./test-env/run-test debian-trixie' \
  cargo nextest run \
    --release \
    --features test-env-vm \
    --test end_to_end \
    --stress-count 20 \
    --test-threads=1 \
    --failure-output immediate-final \
    --success-output never \
    -- \
    "$@"
