name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: cargo hack build --feature-powerset --include-features default,generate-extras --verbose

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: cargo test --bins --features generate-extras --verbose

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          systemd_version="$(systemctl --version | awk 'NR == 1 { print $2 }')"
          [ "${systemd_version}" -ge 256 ] || { echo "Skipping integration tests: systemd ${systemd_version} < 256"; exit 0; }
          sudo apt install debootstrap systemd-container qemu-system-x86 virtiofsd
          ./test-env/setup debian-trixie
          ./test-all --skip ping

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - run: cargo clippy --all-targets --features generate-extras -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv
      - run: cargo msrv verify
